# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField()),
            ],
        ),
    ]
